config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users  

  resources :sessions, only: [:new, :create, :destroy]

  resources :restaurants, only: [:index, :show] do

    resources :reservations, only: [:index, :new, :create, :show, :destroy]

  end

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

	belongs_to :restaurant
	belongs_to :user
    
    validate :can_reserve

    def can_reserve
    	reso_time = restaurant.reservations.where(:date_time => date_time)
    	reso_sizes = reso_time.sum(:party_size)

    	if restaurant.capacity <= party_size + reso_sizes
    		errors.add(:party_size, "restaurant is full at this time, sorreh")
    	end
    end

    def event_date_formatted
    event_date.strftime("%m/%d/%Y")
    end


end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reservations
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :reservations
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    
      @reservation = Reservation.new(reservation_params)
      @reservation.user_id = session[:user_id]
      @reservation.restaurant_id = params[:restaurant_id]
    
    if @reservation.save 
       render 'create'
    else
      render '/restaurants/show'
    end
  end

  def show
    @reservations = Reservation.find(params[:id])
  end

  def destroy
    @reservations = Reservation.find(params[:id])
    @reservations.destroy
  end

  private
  def reservation_params
    params.require(:reservation).permit(:party_size , :date_time)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reservation = Reservation.new
  end

  # def new
  #   @restaurant = Restaurant.new
  # end

  def create 
    @restaurant = Restaurant.new
    @restaurant.save
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new

	end

	def create
		user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to restaurants_url, notice: "Logged in!"
		else
			render "new"
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url, notice: "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_session_path
    else
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeatYourself</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

app/views/reservations/index.html.erb
<h1>Reservations#index</h1>
<p>Find me in app/views/reservations/index.html.erb</p>

app/views/reservations/new.html.erb
<h1>Make a Reservation at <%= @restaurants.name %></h1>



<select name="time">
 <option value="8">8AM</option>
 <option value="9">9AM</option>
 <option value="10">10AM</option>
</select>



<%= select_month(Date.today) %>
<%= select_year(Date.today, :start_year => Date.today.year, :end_year => 3.years.from_now.year) %>

app/views/reservations/show.html.erb
<h1>Reservations#show</h1>
<p>Find me in app/views/reservations/show.html.erb</p>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>


  <table>

    <tr>
      <th>Restaurant Name</th>
      <th>Address</th>
      <th>Price Range</th>
      <th>Make a Reservation</th>
    </tr>

    <% @restaurants.each do |r| %>

      <tr>
        <td><%= r.name %></td>
        <td><%= r.address %></td>
        <td><%= r.price_range %></td>
        <td><%= link_to "RESERVE", restaurant_path(r.id) %></td> 
      </tr>

    <% end %>

  </table>

app/views/restaurants/show.html.erb
<h1>Make a Reservation at <%= @restaurant.name %></h1>

<%= form_for [@restaurant, @reservation] do |f| %>
<% @reservation.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>

<%= f.label :party_size %>
<%= f.text_field :party_size %>

<%= f.label :date_time %>
<%= f.datetime_select :date_time %>

<%= f.submit "Make yo reservation" %>

<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Sign UP <i>my precious</i></h1>


<%= form_for(@user) do |f| %>
	<div class = "field">
		<%= f.label :firstname %><br/>
		<%= f.text_field :firstname %>
	</div>

	<div class="field">
		<%= f.label :lastname %><br/>
		<%= f.text_field :lastname %>
	</div>

	<div class="field">
		<%= f.label :email %><br/>
		<%= f.text_field :email %>
	</div>

	<div class="field">
		<%= f.label :password %><br/>
		<%= f.password_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation %><br/>
		<%= f.password_field :password_confirmation %>
	</div>

	<div class="submit">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome to Seat Yo'self!</h1>

<%= link_to "Sign up", new_user_path %>

<%= link_to "Sign In", new_session_path %>